
name: Production Deployment

on:
  push:
    branches:
      - main

jobs:
  production-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build Angular Project
      run: npm run build --if-present

    - name: Verify Build Directory
      run: ls -ld ${{ github.workspace }}/dist/my-angular-app/

    - name: Deploy to EC2
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "${{ github.workspace }}/dist/my-angular-app/"
        REMOTE_HOST: "13.233.152.138"
        REMOTE_USER: "ubuntu"
        TARGET: "/var/www/html/angular-demo/"
